spring:
  profiles:
    active: local
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aejimeongji?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  #    show-sql: true
  messages:
    basename: messages
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  http:
    multipart:
      maxFilezie: 300MB
      maxRequestSize: 300MB
logging:
  level:
#    root: debug
    org.hibernate.SQL: debug
    org.springframework.web: debug
    org.springframework.security: trace
#    org.hibernate.type: trace
    com.ssafy.aejimeongji: debug
    p6spy: info

coolsms:
  apiKey: NCSHUZ8V9NAHIDQ7
  apiSecret: BRQ6IFOTVUMLDTMOWON8WQZGWZGP4VNF

jwt:
  secretKey: ssafygumi2class3teamfightingkdhpgypje

file:
  dir: C:\Users\multicampus\Desktop\dohyeon
