version: "3"
services:
  mysql:
    build: ./mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/docker-volume/database/initdata:/docker-entrypoint-initdb.d/
      - /home/ubuntu/docker-volume/database/datadir:/var/lib/mysql

  redis:
    build: ./redis
    restart: always
    ports:
      - 6379:6379

  react:
    build: ./front
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - springboot

  springboot:
    build: ./back
    ports:
      - 8080:8080
    volumes:
      - /home/ubuntu/docker-volume/images:/images
    depends_on:
      - mysql
      - redis

  nginx:
    build: ./nginx
    ports:
      - 80:80
    # volumes:
    #   - /home/ubuntu/docker-volume/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - react
